In [2]:
testing = 1
testing = testing + 1
print(str(testing))

2

In [3]:
import numpy as np
import pandas as pd

myDF = pd.DataFrame([1, 2, 3])
myDF.

   0
0  1
1  2
2  3